version: '3'

services:
# Loadbalancer server configuration   
  loadbalancer:
    image: nginx:stable
    container_name: loadbalancer
    networks:
      - main-network
    volumes:
      - ./Docker/nginx/loadbalancer.conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
 # Nginx server configuration   
  web:
    image: nginx:stable
    container_name: webserver
    depends_on:
      - loadbalancer
      - mysql
      - php
    networks:
      main-network:
        aliases:
          - "acsc476.web"
    volumes:
      - ./app:/var/www/order.io/
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8088:8088"
 # Php-fpm configuration
  php:
    build:
      context: .
      dockerfile: ./Docker/php/DockerFile
    image: php:8.1-fpm
    networks:
      - main-network
    depends_on:
      - loadbalancer
    volumes:
      - ./app:/var/www/order.io/
      - ./Docker/php/conf/php.ini:/usr/local/etc/php/php.ini
 # Mysql configuration
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: acsc476-mysql
    restart: always
    networks:
      main-network:
        aliases:
          - "acsc476.db"
    environment:
        - MYSQL_DATABASE=dashboard
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3309:3306"
    volumes:
        - dashboard_data:/var/lib/mysql
# Volumes
volumes:
  dashboard_data:
    driver: local
# Networks
networks:
  main-network:
    driver: bridge