version: '3'

services:
# Loadbalancer server configuration   
  loadbalancer:
    image: nginx:stable
    container_name: loadbalancer
    volumes:
      - ./Docker/nginx/loadbalancer.conf.d/:/etc/nginx/conf.d/
    network_mode: host
 # Nginx server configuration   
  web:
    image: nginx:stable
    container_name: webserver
    depends_on:
      - loadbalancer
      - mysql
      - php
    links:
      - mysql
      - php
    volumes:
      - ./html:/var/www/html
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8088:8088"
 # Php-fpm configuration
  php:
    image: php:8.1-fpm
    volumes:
      - ./html:/var/www/html
      - ./Docker/php:/usr/local/etc/php/php.ini
 # Mysql configuration
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: acsc476-mysql
    restart: always
    environment:
        - MYSQL_DATABASE=dashboard
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3309:3306"
    volumes:
        - dashboard_data:/var/lib/mysql
# Volumes
volumes:
  dashboard_data:
    driver: local